-- Database: UrlShorter

-- DROP DATABASE IF EXISTS "UrlShorter";

CREATE DATABASE "UrlShorter"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Turkish_Turkey.1254'
    LC_CTYPE = 'Turkish_Turkey.1254'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clicks
(
    token text COLLATE pg_catalog."default" NOT NULL,
    urltoken text COLLATE pg_catalog."default" NOT NULL,
    ip text COLLATE pg_catalog."default" NOT NULL,
    country text COLLATE pg_catalog."default" NOT NULL,
    city text COLLATE pg_catalog."default" NOT NULL,
    latitude text COLLATE pg_catalog."default" NOT NULL,
    longitude text COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.urls
(
    token text COLLATE pg_catalog."default" NOT NULL,
    ownertoken text COLLATE pg_catalog."default" NOT NULL,
    redirect text COLLATE pg_catalog."default" NOT NULL,
    click integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users
(
    token text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    perm text COLLATE pg_catalog."default" NOT NULL
);
END;
